/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Casino-transformed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/casino/Casino-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.25, 0]} scale={0.025}>
        <mesh geometry={nodes.ID5.geometry} material={materials.__auto_} />
        <mesh geometry={nodes.ID5_1.geometry} material={materials.material_1} />
      </group>
      <mesh geometry={nodes.instance_0072.geometry} material={materials.__auto_1} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_0080.geometry} material={materials.__auto_3} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_01426.geometry} material={materials.__auto_24} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_01818.geometry} material={materials.__auto_16} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_01885.geometry} material={materials.__auto_29} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_01901.geometry} material={materials.__auto_34} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_0221.geometry} material={materials.__auto_4} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_02874.geometry} material={materials.__auto_44} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_03488.geometry} material={materials.__auto_58} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes.instance_0736.geometry} material={materials.__auto_20} position={[0, 0.25, 0]} scale={0.025} />
      <mesh geometry={nodes['Line003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 0.356, -0.928]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/casino//Casino-transformed.glb')
