/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blackjack_table.gltf 
Author: Ravi Jangid (https://sketchfab.com/ravijangid.rv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackjack-table-baf7e3cbd14140ca81ea1a79d28fb635
Title: Blackjack Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}blackjack_table/blackjack_table.gltf`)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.704}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <mesh geometry={nodes['Rectangle001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 504.046, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Rectangle004_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 508.561, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Rectangle005_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 504.572, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Rectangle006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 0, 249.047]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Shape001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 301.429, 249.047]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Shape002_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 100.548, 249.047]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.015, 64.552, 1071.126]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line004_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-315.259, 64.552, 982.723]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line005_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-540.969, 64.552, 748.752]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-611.736, 64.552, 503.525]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line007_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[611.564, 64.552, 503.525]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line008_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[540.798, 64.552, 748.752]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line009_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[315.088, 64.552, 982.723]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}blackjack_table/blackjack_table.gltf`)
