/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\card_deck.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({card, position, rotation, props}) {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}card_deck/card_deck.gltf`)

  if(card){
    return(
      <group position={position} rotation={rotation} scale={[0.003, 0.0025, 0.003]} {...props}>
        {
          card.meshes.map((m, i) => (
            <mesh
            key={i}
              geometry={nodes[m.mesh].geometry}
              material={materials[m.materials]}
            />
          ))
        }
      </group>
    )
  }

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI * 0.5, 0, 0]} scale={0.0025} position={[0, 0.87, 0]}>
        <group rotation={[0, 0, 0]}>
          <group position={[-364.902, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ace_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ace_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Ace_of_Clubs_27_0'].geometry} material={materials['material_41.002']} />
          </group>
          <group position={[-364.902, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ace_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ace_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ace_of_Clubs_27_0.geometry} material={materials['material_41.002']} />
          </group>
          <group position={[-364.902, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ace_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ace_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ace_of_Diamonds_13_0.geometry} material={materials['material_28.002']} />
          </group>
          <group position={[-364.902, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ace_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ace_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ace_of_Hearts_1_0.geometry} material={materials['material.002']} />
          </group>
          <group position={[-364.902, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ace_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ace_of_Spades_02_-_Default_0'].geometry} material={materials['02_-_Default.002']} />
            <mesh geometry={nodes['Ace_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
          </group>
          <group position={[60.294, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Eigh_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Eigh_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Eigh_of_Hearts_8_0.geometry} material={materials['material_16.002']} />
          </group>
          <group position={[60.294, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Eight_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Eight_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Eight_of_Clubs_34_0.geometry} material={materials['material_42.002']} />
          </group>
          <group position={[60.294, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Eight_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Eight_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Eight_of_Diamonds_22_0.geometry} material={materials['material_29.002']} />
          </group>
          <group position={[60.294, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Eight_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Eight_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Eight_of_Spades_19_-_Default_0'].geometry} material={materials['19_-_Default.002']} />
          </group>
          <group position={[-121.933, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Five_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Five_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Five_of_Clubs_31_0.geometry} material={materials['material_43.002']} />
          </group>
          <group position={[-121.933, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Five_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Five_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Five_of_Diamonds_18_0.geometry} material={materials['material_30.002']} />
          </group>
          <group position={[-121.933, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Five_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Five_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Five_of_Hearts_5_0.geometry} material={materials['material_17.002']} />
          </group>
          <group position={[-121.933, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Five_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Five_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Five_of_Spades_13_-_Default_0'].geometry} material={materials['13_-_Default.002']} />
          </group>
          <group position={[-182.675, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Four_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Four_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Four_of_Clubs_30_0.geometry} material={materials['material_44.002']} />
          </group>
          <group position={[-182.675, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Four_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Four_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Four_of_Diamonds_17_0.geometry} material={materials['material_31.002']} />
          </group>
          <group position={[-182.675, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Four_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Four_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Four_of_Hearts_4_0.geometry} material={materials['material_18.002']} />
          </group>
          <group position={[-182.675, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Four_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Four_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Four_of_Spades_09_-_Default_0'].geometry} material={materials['09_-_Default.002']} />
          </group>
          <group position={[242.52, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Jack_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Jack_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Jack_of_Clubs_37_0.geometry} material={materials['material_45.002']} />
          </group>
          <group position={[242.52, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Jack_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Jack_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Jack_of_Diamonds_25_0.geometry} material={materials['material_32.002']} />
          </group>
          <group position={[242.52, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Jack_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Jack_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Jack_of_Hearts_11_0.geometry} material={materials['material_19.002']} />
          </group>
          <group position={[242.52, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Jack_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Jack_of_Spades_04_-_Default_0'].geometry} material={materials['04_-_Default.002']} />
            <mesh geometry={nodes['Jack_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
          </group>
          <group position={[364.005, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['King_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['King_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.King_of_Clubs_43_0.geometry} material={materials['material_46.002']} />
          </group>
          <group position={[364.005, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['King_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['King_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['King_of_Diamonds_22_-_Default_0'].geometry} material={materials['22_-_Default.002']} />
          </group>
          <group position={[364.005, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['King_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['King_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.King_of_Hearts_14_0.geometry} material={materials['material_20.002']} />
          </group>
          <group position={[364.005, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['King_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['King_of_Spades_06_-_Default_0'].geometry} material={materials['06_-_Default.002']} />
            <mesh geometry={nodes['King_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
          </group>
          <group position={[121.036, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Nine_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Nine_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Nine_of_Clubs_35_0.geometry} material={materials['material_47.002']} />
          </group>
          <group position={[121.036, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Nine_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Nine_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Nine_of_Diamonds_23_0.geometry} material={materials['material_34.002']} />
          </group>
          <group position={[121.036, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Nine_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Nine_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Nine_of_Hearts_9_0.geometry} material={materials['material_21.002']} />
          </group>
          <group position={[121.036, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Nine_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Nine_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Nine_of_Spades_20_-_Default_0'].geometry} material={materials['20_-_Default.002']} />
          </group>
          <group position={[303.263, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Queen_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Queen_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Queen_of_Clubs_39_0.geometry} material={materials['material_48.002']} />
          </group>
          <group position={[303.263, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Queen_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Queen_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Queen_of_Diamonds_26_0.geometry} material={materials['material_35.002']} />
          </group>
          <group position={[303.263, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Queen_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Queen_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Queen_of_Hearts_12_0.geometry} material={materials['material_22.002']} />
          </group>
          <group position={[303.263, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Queen_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Queen_of_Spades_05_-_Default_0'].geometry} material={materials['05_-_Default.002']} />
            <mesh geometry={nodes['Queen_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
          </group>
          <group position={[-0.449, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Seven_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Seven_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Seven_of_Clubs_33_0.geometry} material={materials['material_49.002']} />
          </group>
          <group position={[-0.449, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Seven_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Seven_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Seven_of_Diamonds_21_0.geometry} material={materials['material_36.002']} />
          </group>
          <group position={[-0.449, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Seven_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Seven_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Seven_of_Hearts_7_0.geometry} material={materials['material_23.002']} />
          </group>
          <group position={[-0.449, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Seven_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Seven_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Seven_of_Spades_15_-_Default_0'].geometry} material={materials['15_-_Default.002']} />
          </group>
          <group position={[-61.191, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Six_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Six_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Six_of_Clubs_32_0.geometry} material={materials['material_50.002']} />
          </group>
          <group position={[-61.191, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Six_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Six_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Six_of_Diamonds_20_0.geometry} material={materials['material_37.002']} />
          </group>
          <group position={[-61.191, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Six_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Six_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Six_of_Hearts_6_0.geometry} material={materials['material_24.002']} />
          </group>
          <group position={[-61.191, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Six_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Six_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Six_of_Spades_14_-_Default_0'].geometry} material={materials['14_-_Default.002']} />
          </group>
          <group position={[181.778, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ten_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ten_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ten_of_Clubs_36_0.geometry} material={materials['material_51.002']} />
          </group>
          <group position={[181.778, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ten_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ten_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ten_of_Diamonds_24_0.geometry} material={materials['material_38.002']} />
          </group>
          <group position={[181.778, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ten_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ten_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Ten_of_Hearts_10_0.geometry} material={materials['material_25.002']} />
          </group>
          <group position={[181.778, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Ten_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Ten_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Ten_of_Spades_21_-_Default_0'].geometry} material={materials['21_-_Default.002']} />
          </group>
          <group position={[-243.417, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Three_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Three_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Three_of_Clubs_29_0.geometry} material={materials['material_52.002']} />
          </group>
          <group position={[-243.417, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Three_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Three_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Three_of_Diamonds_16_0.geometry} material={materials['material_39.002']} />
          </group>
          <group position={[-243.417, 52.903, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Three_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Three_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Three_of_Hearts_3_0.geometry} material={materials['material_26.002']} />
          </group>
          <group position={[-243.417, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Three_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Three_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes['Three_of_Spades_08_-_Default_0'].geometry} material={materials['08_-_Default.002']} />
          </group>
          <group position={[-304.16, -156.008, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Two_of_Clubs_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Two_of_Clubs_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Two_of_Clubs_28_0.geometry} material={materials['material_53.002']} />
          </group>
          <group position={[-304.16, -50.777, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Two_of_Diamonds_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Two_of_Diamonds_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Two_of_Diamonds_15_0.geometry} material={materials['material_40.002']} />
          </group>
          <group position={[-304.16, 54.455, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Two_of_Hearts_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Two_of_Hearts_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
            <mesh geometry={nodes.Two_of_Hearts_2_0.geometry} material={materials['material_27.002']} />
          </group>
          <group position={[-304.16, 159.687, 5.387]} scale={[1.122, 1, 0.492]}>
            <mesh geometry={nodes['Two_of_Spades_01_-_Default_0'].geometry} material={materials['01_-_Default.003']} />
            <mesh geometry={nodes['Two_of_Spades_03_-_Default_0'].geometry} material={materials['03_-_Default.002']} />
            <mesh geometry={nodes['Two_of_Spades_07_-_Default_0'].geometry} material={materials['07_-_Default.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}card_deck/card_deck.gltf`)
