/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ..\..\public\dealer\Dealer.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('dealer/Dealer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && actions["mixamo.com.008"]) {
      actions["mixamo.com.008"].play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null} position={[0, -1.2, -1]}>
      <group name="Scene">
        <group name="AvatarTeethLower" />
        <group name="AvatarLeftCornea" />
        <group name="outfit" />
        <group name="AvatarRightEyeball" />
        <group name="AvatarLeftEyeball" />
        <group name="AvatarRightCornea" />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['AvatarLeftCornea.008']} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['AvatarLeftEyeball.008']} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['AvatarRightCornea.008']} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['AvatarRightEyeball.008']} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['AvatarTeethLower.008']} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['AvatarTeethUpper.008']} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['glasses.008']} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['outfit.008']} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['AvatarBody.008']} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['AvatarEyelashes.008']} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['AvatarHead.008']} skeleton={nodes.Object_9.skeleton} />
        </group>
        <group name="AvatarEyelashes" />
        <group name="glasses" />
        <group name="AvatarBody" />
        <group name="AvatarTeethUpper" />
        <group name="AvatarHead" />
      </group>
    </group>
  )
}

useGLTF.preload('dealer/Dealer.glb')
