name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: Blackjack

      - name: Setup Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
        working-directory: Blackjack

      - name: Build the project
        run: npm run build
        working-directory: Blackjack

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist
        working-directory: Blackjack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}